//third_party/javascript/css_element_queries/dist/ResizeSensor.min.js
/**
 * @description Polyfill for element based media-queries.
 * @version 1.0.2
 * @author Marc J. Schmidt
 * @url http://marcj.github.io/css-element-queries/
 * @license
 * Copyright (c) 2013 Marc J. Schmidt
 *
 * Use of this source code is governed by a MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */
(function(f,d){"function"===typeof define&&define.amd?define(d):"object"===typeof exports?module.exports=d():f.ResizeSensor=d()})("undefined"!==typeof window?window:this,function(){function f(a,e){var c=Object.prototype.toString.call(a),d=0,b=a.length;if("[object Array]"===c||"[object NodeList]"===c||"[object HTMLCollection]"===c||"[object Object]"===c||"undefined"!==typeof jQuery&&a instanceof jQuery||"undefined"!==typeof Elements&&a instanceof Elements)for(;d<b;d++)e(a[d]);else e(a)}function d(a){if(!a.getBoundingClientRect)return{width:a.offsetWidth,
height:a.offsetHeight};a=a.getBoundingClientRect();return{width:Math.round(a.width),height:Math.round(a.height)}}if("undefined"===typeof window)return null;var m=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,20)},g=function(a,e){function c(){var b=[];this.add=function(a){b.push(a)};var a,c;this.call=function(){a=0;for(c=b.length;a<c;a++)b[a].call()};this.remove=function(t){var d=[];a=0;for(c=b.length;a<c;a++)b[a]!==
t&&d.push(b[a]);b=d};this.length=function(){return b.length}}function h(b,a){if(b)if(b.resizedAttached)b.resizedAttached.add(a);else{b.resizedAttached=new c;b.resizedAttached.add(a);b.resizeSensor=document.createElement("div");b.resizeSensor.dir="ltr";b.resizeSensor.className="resize-sensor";b.resizeSensor.style.cssText="position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;";b.resizeSensor.innerHTML='<div class="resize-sensor-expand" style="position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0; top: 0; transition: 0s;"></div></div><div class="resize-sensor-shrink" style="position: absolute; left: -10px; top: -10px; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;"><div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div></div>';
b.appendChild(b.resizeSensor);a=window.getComputedStyle(b).getPropertyValue("position");"absolute"!==a&&"relative"!==a&&"fixed"!==a&&(b.style.position="relative");var e=b.resizeSensor.childNodes[0],f=e.childNodes[0],g=b.resizeSensor.childNodes[1],n,k;a=d(b);var p=a.width,q=a.height,l=function(){var a=0===b.offsetWidth&&0===b.offsetHeight;if(a){var c=b.style.display;b.style.display="block"}f.style.width="100000px";f.style.height="100000px";e.scrollLeft=1E5;e.scrollTop=1E5;g.scrollLeft=1E5;g.scrollTop=
1E5;a&&(b.style.display=c)};b.resizeSensor.resetSensor=l;var h=function(){k=0;n&&(q=p=void 0,b.resizedAttached&&b.resizedAttached.call())};a=function(){var a=d(b),c=a.height;(n=a.width!=p||c!=q)&&!k&&(k=m(h));l()};var r=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c)};r(e,"scroll",a);r(g,"scroll",a);m(l)}}f(a,function(a){h(a,e)});this.detach=function(b){g.detach(a,b)};this.reset=function(){a.resizeSensor.resetSensor()}};g.reset=function(a,d){f(a,function(a){a.resizeSensor.resetSensor()})};
g.detach=function(a,d){f(a,function(a){if(a){if(a.resizedAttached&&"function"===typeof d&&(a.resizedAttached.remove(d),a.resizedAttached.length()))return;a.resizeSensor&&(a.contains(a.resizeSensor)&&a.removeChild(a.resizeSensor),delete a.resizeSensor,delete a.resizedAttached)}})};return g});

//third_party/javascript/css_element_queries/dist/ElementQueries.min.js
/**
 * @description Polyfill for element based media-queries.
 * @version 1.0.2
 * @author Marc J. Schmidt
 * @url http://marcj.github.io/css-element-queries/
 * @license
 * Copyright (c) 2013 Marc J. Schmidt
 *
 * Use of this source code is governed by a MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */
(function(k,c){"function"===typeof define&&define.amd?define(["./ResizeSensor.js"],c):"object"===typeof exports?module.exports=c(require("./ResizeSensor.js")):(k.ElementQueries=c(k.ResizeSensor),k.ElementQueries.listen())})("undefined"!==typeof window?window:this,function(k){var c=function(){function c(a){a||(a=document.documentElement);a=window.getComputedStyle(a,null).fontSize;return parseFloat(a)||16}function t(a,b){var d=b.split(/\d/);d=d[d.length-1];b=parseFloat(b);switch(d){case "px":return b;
case "em":return b*c(a);case "rem":return b*c();case "vw":return b*document.documentElement.clientWidth/100;case "vh":return b*document.documentElement.clientHeight/100;case "vmin":case "vmax":return b*(0,Math["vmin"===d?"min":"max"])(document.documentElement.clientWidth/100,document.documentElement.clientHeight/100);default:return b}}function x(a,b){var d,l;this.element=a;var h,c,g,e,f,n,p,q=["min-width","min-height","max-width","max-height"];this.call=function(){var a=this.element;a.getBoundingClientRect?
(a=a.getBoundingClientRect(),d=Math.round(a.width),l=Math.round(a.height)):(d=a.offsetWidth,l=a.offsetHeight);f={};for(h in m[b])m[b].hasOwnProperty(h)&&(c=m[b][h],g=t(this.element,c.value),e="width"===c.property?d:l,p=c.mode+"-"+c.property,n="","min"===c.mode&&e>=g&&(n+=c.value),"max"===c.mode&&e<=g&&(n+=c.value),f[p]||(f[p]=""),n&&-1===(" "+f[p]+" ").indexOf(" "+n+" ")&&(f[p]+=" "+n));for(var r in q)q.hasOwnProperty(r)&&(f[q[r]]?this.element.setAttribute(q[r],f[q[r]].substr(1)):this.element.removeAttribute(q[r]))}}
function y(a,b){a.elementQueriesSetupInformation||(a.elementQueriesSetupInformation=new x(a,b));a.elementQueriesSensor||(a.elementQueriesSensor=new k(a,function(){a.elementQueriesSetupInformation.call()}));a.elementQueriesSetupInformation.call()}function z(a){var b;document.querySelectorAll&&(b=a?a.querySelectorAll.bind(a):document.querySelectorAll.bind(document));b||"undefined"===typeof $$||(b=$$);b||"undefined"===typeof jQuery||(b=jQuery);if(!b)throw"No document.querySelectorAll, jQuery or Mootools's $$ found.";
return b}function B(a){function b(){var b=!1;for(l in d)d.hasOwnProperty(l)&&c[l].minWidth&&a.offsetWidth>c[l].minWidth&&(b=l);b||(b=g);if(e!==b)if(m[b])d[e].style.display="none",d[b].style.display="block",e=b;else{var l=new Image;l.onload=function(){d[b].src=h[b];d[e].style.display="none";d[b].style.display="block";m[b]=!0;e=b};l.src=h[b]}else d[b].src=h[b]}var d=[],c=[],h=[],g=0,e=-1,m=[],f;for(f in a.children)if(a.children.hasOwnProperty(f)&&a.children[f].tagName&&"img"===a.children[f].tagName.toLowerCase()){d.push(a.children[f]);
var n=a.children[f].getAttribute("min-width")||a.children[f].getAttribute("data-min-width"),p=a.children[f].getAttribute("data-src")||a.children[f].getAttribute("url");h.push(p);c.push({minWidth:n});n?a.children[f].style.display="none":(g=d.length-1,a.children[f].style.display="block")}e=g;a.resizeSensor=new k(a,b);b()}function C(){for(var a=z()("[data-responsive-image],[responsive-image]"),b=0,d=a.length;b<d;b++)B(a[b])}function u(a){var b,d;for(a=a.replace(/'/g,'"');null!==(b=D.exec(a));){var c=
b[1]+b[3];for(b=b[2];null!==(d=E.exec(b));){var h=c,g=d[1],k=d[2];d=d[3];if("undefined"===typeof m[h]){m[h]=[];var t=v.length;e.innerHTML+="\n"+h+" {animation: 0.1s element-queries;}";e.innerHTML+="\n"+h+" > .resize-sensor {min-width: "+t+"px;}";v.push(h)}m[h].push({mode:g,property:k,value:d})}}}function w(a){if(a)if("string"===typeof a)a=a.toLowerCase(),-1===a.indexOf("min-width")&&-1===a.indexOf("max-width")||u(a);else for(var b=0,d=a.length;b<d;b++)if(1===a[b].type){var c=a[b].selectorText||a[b].cssText;
-1!==c.indexOf("min-height")||-1!==c.indexOf("max-height")?u(c):(-1!==c.indexOf("min-width")||-1!==c.indexOf("max-width"))&&u(c)}else 4===a[b].type?w(a[b].cssRules||a[b].rules):3===a[b].type&&a[b].styleSheet.hasOwnProperty("cssRules")&&w(a[b].styleSheet.cssRules)}var e,m={},v=[],D=/,?[\s\t]*([^,\n]*?)((?:\[[\s\t]*?(?:min|max)-(?:width|height)[\s\t]*?[~$\^]?=[\s\t]*?"[^"]*?"[\s\t]*?])+)([^,\n\s\{]*)/mgi,E=/\[[\s\t]*?(min|max)-(width|height)[\s\t]*?[~$\^]?=[\s\t]*?"([^"]*?)"[\s\t]*?]/mgi,A=!1;this.init=
function(){var a="animationstart";"undefined"!==typeof document.documentElement.style.webkitAnimationName?a="webkitAnimationStart":"undefined"!==typeof document.documentElement.style.MozAnimationName?a="mozanimationstart":"undefined"!==typeof document.documentElement.style.OAnimationName&&(a="oanimationstart");document.body.addEventListener(a,function(a){var b=a.target;if(-1!==window.getComputedStyle(b,null).getPropertyValue("animation-name").indexOf("element-queries")){b.elementQueriesSensor=new k(b,
function(){b.elementQueriesSetupInformation&&b.elementQueriesSetupInformation.call()});var c=window.getComputedStyle(b.resizeSensor,null).getPropertyValue("min-width");c=parseInt(c.replace("px",""));y(a.target,v[c])}});A||(e=document.createElement("style"),e.type="text/css",e.innerHTML="[responsive-image] > img, [data-responsive-image] {overflow: hidden; padding: 0; } [responsive-image] > img, [data-responsive-image] > img {width: 100%;}",e.innerHTML+="\n@keyframes element-queries { 0% { visibility: inherit; } }",
document.getElementsByTagName("head")[0].appendChild(e),A=!0);a=0;for(var b=document.styleSheets.length;a<b;a++)try{document.styleSheets[a].href&&0===document.styleSheets[a].href.indexOf("file://")&&console.log("CssElementQueries: unable to parse local css files, "+document.styleSheets[a].href),w(document.styleSheets[a].cssRules||document.styleSheets[a].rules||document.styleSheets[a].cssText)}catch(d){}C()};this.findElementQueriesElements=function(a){var b=z(a),c;for(c in m)if(m.hasOwnProperty(c))for(var g=
b(c,a),e=0,k=g.length;e<k;e++)y(g[e],c)};this.update=function(){this.init()}};c.update=function(){c.instance.update()};c.detach=function(c){c.elementQueriesSetupInformation?(c.elementQueriesSensor.detach(),delete c.elementQueriesSetupInformation,delete c.elementQueriesSensor):c.resizeSensor&&(c.resizeSensor.detach(),delete c.resizeSensor)};c.init=function(){c.instance||(c.instance=new c);c.instance.init()};var x=function(c){if(document.addEventListener)document.addEventListener("DOMContentLoaded",
c,!1);else if(/KHTML|WebKit|iCab/i.test(navigator.userAgent))var g=setInterval(function(){/loaded|complete/i.test(document.readyState)&&(c(),clearInterval(g))},10);else window.onload=c};c.findElementQueriesElements=function(g){c.instance.findElementQueriesElements(g)};c.listen=function(){x(c.init)};return c});

